load("@rules_python//python:defs.bzl", "py_library", "py_test")
load("@sonic_apt_pip//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "lib",
    srcs = glob(["sonic_apt/*.py"]),
    imports = ["."],
    deps = [requirement("python-debian")],
)

py_test(
    name = "selection_test",
    srcs = ["tests/selection_test.py"],
    deps = [":lib"],
)

py_test(
    name = "inputs_test",
    srcs = ["tests/inputs_test.py"],
    deps = [":lib"],
)

py_test(
    name = "dependencies_test",
    srcs = ["tests/dependencies_test.py"],
    deps = [":lib"],
)

exports_files(["export_inputs.py", "requirements_lock.txt"])
