#!/usr/bin/env python3
"""Generate crate_universe metadata before a SONiC Bazel build (Python 3.11+)."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import tomllib
from urllib.parse import urlsplit, urlunsplit


RC_MARKER = "# Generated by sonic-build-infra tools/rust/prepare.py; do not edit.\n"


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def local_path(workspace, value):
    path = (workspace / value).resolve()
    if not path.is_relative_to(workspace):
        raise ValueError(f"Path must stay inside the workspace: {value}")
    return path


def verify_graph(cargo_bytes, generated):
    """Reject any selected package whose version or source differs from Cargo.lock."""
    packages = tomllib.loads(cargo_bytes.decode())["package"]
    by_id = {}
    for package in packages:
        key = (package["name"], package["version"])
        by_id.setdefault(key, []).append(package)
    crates = generated.get("crates")
    if not isinstance(crates, dict) or not crates:
        raise ValueError("Generated metadata has no crates")
    selected = []
    for identifier, crate in sorted(crates.items()):
        key = (crate["name"], crate["version"])
        matches = by_id.get(key, [])
        repository = crate.get("repository")
        matching = []
        for package in matches:
            source = package.get("source", "")
            if not repository:
                valid = not source
            elif "Http" in repository:
                checksum = repository["Http"].get("sha256")
                valid = (source.startswith("registry+") and bool(checksum)
                         and checksum == package.get("checksum"))
            elif "Git" in repository:
                git = repository["Git"]
                parsed = urlsplit(source.removeprefix("git+"))
                remote = urlunsplit((parsed.scheme, parsed.netloc, parsed.path, "", ""))
                valid = (source.startswith("git+") and bool(parsed.fragment)
                         and git.get("remote") == remote
                         and git.get("commitish") == {"Rev": parsed.fragment})
            else:
                valid = False
            if valid:
                matching.append(package)
        if len(matching) != 1:
            raise ValueError(f"Generated crate does not match one Cargo.lock pin: {identifier}")
        pin = matching[0]
        selected.append({field: pin[field] for field in ("name", "version", "source", "checksum") if field in pin})
    return selected


def run_bazel(args, workspace, command, arguments=(), *, env=None, capture=False):
    startup = list(args.bazel_startup_arg)
    if workspace != getattr(args, "workspace", workspace):
        # setup-bazel can set a shared output_base in an ambient bazelrc. A
        # different workspace must never reuse or kill the consumer's server.
        output_base = workspace.parent / (".bazel-output-" + workspace.name)
        startup = [flag for flag in startup if not flag.startswith("--output_base=")]
        startup.append("--output_base=" + str(output_base))
        if "--batch" not in startup:
            startup.append("--batch")
    invocation = [args.bazel, *startup, command,
                  *args.bazel_arg, "--lockfile_mode=update", *arguments]
    completed = subprocess.run(invocation, cwd=workspace, env=env, check=True,
                               text=True, stdout=subprocess.PIPE if capture else None)
    return completed.stdout if capture else invocation


def prepare_one(args, workspace, repository, cargo_name, generated_name, receipt):
    cargo = local_path(workspace, cargo_name)
    if (workspace / generated_name).is_symlink():
        raise ValueError("Generated metadata must not be a symlink")
    output = local_path(workspace, generated_name)
    if output == cargo or receipt.resolve() in (cargo, output):
        raise ValueError("Cargo.lock, generated metadata and receipt must be different files")
    before = cargo.read_bytes()
    # Resolve stale caches by regeneration, never by accepting a restored receipt.
    # The empty file lets Bazel resolve the configured source-file label first.
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(b"")
    receipt.unlink(missing_ok=True)
    env = os.environ.copy()
    env.pop("REPIN", None)
    env.pop("CARGO_BAZEL_REPIN_ONLY", None)
    env["CARGO_BAZEL_REPIN"] = "workspace"
    try:
        command = run_bazel(args, workspace, "fetch", ["--repo=@" + repository], env=env)
        if cargo.read_bytes() != before:
            raise ValueError("Preparation changed Cargo.lock; use skip_cargo_lockfile_overwrite = True")
        generated_bytes = output.read_bytes()
        graph = verify_graph(before, json.loads(generated_bytes))
        inputs = {"MODULE.bazel": sha256((workspace / "MODULE.bazel").read_bytes())}
        for name in (".bazelversion", ".bazelrc"):
            if (workspace / name).is_file():
                inputs[name] = sha256((workspace / name).read_bytes())
        # Cargo workspaces can have nested manifests; retain them as provenance.
        for manifest in workspace.rglob("Cargo.toml"):
            if not any(part.startswith((".git", "bazel-", ".cargo-bazel")) for part in manifest.relative_to(workspace).parts):
                inputs[str(manifest.relative_to(workspace))] = sha256(manifest.read_bytes())
        result = {
            "schema_version": 1,
            "workspace": str(workspace),
            "repository": repository,
            "cargo_lock": cargo_name,
            "cargo_lock_sha256": sha256(before),
            "cargo_lock_unchanged": True,
            "bazel_lock": generated_name,
            "bazel_lock_sha256": sha256(generated_bytes),
            "helper_sha256": sha256(Path(__file__).read_bytes()),
            "input_sha256": inputs,
            "selected_packages": graph,
            "command": command,
        }
        write_json(receipt, result)
        return result
    except BaseException:
        # A failed preparation must not leave a usable stale/partially written lock.
        output.unlink(missing_ok=True)
        if not cargo.is_file() or cargo.read_bytes() != before:
            cargo.write_bytes(before)
        raise


def stage_dependency(args, workspace, module, apparent, staging):
    """Fetch the already declared module; do not evaluate its crate extension yet."""
    raw_mapping = run_bazel(args, workspace, "mod", ["dump_repo_mapping", ""], capture=True)
    # Some JDKs write startup diagnostics to stdout before the NDJSON payload.
    mapping_lines = [line for line in raw_mapping.splitlines() if line.startswith("{")]
    if len(mapping_lines) != 1:
        raise ValueError("Expected one root repository mapping from Bazel")
    mapping = json.loads(mapping_lines[0])
    canonical = mapping[apparent]
    run_bazel(args, workspace, "fetch", ["--repo=@@" + canonical])
    raw_info = run_bazel(args, workspace, "info", ["output_base"], capture=True)
    paths = [Path(line) for line in raw_info.splitlines() if Path(line).is_absolute()]
    if len(paths) != 1:
        raise ValueError("Expected one absolute output_base from Bazel")
    output_base = paths[0]
    source = output_base / "external" / canonical
    if not (source / "MODULE.bazel").is_file():
        raise ValueError(f"Resolved module has no source directory: {source}")
    staging.mkdir(parents=True, exist_ok=True)
    destination = Path(tempfile.mkdtemp(prefix=module + "-", dir=staging))
    shutil.copytree(source, destination, dirs_exist_ok=True, symlinks=False,
                    ignore=shutil.ignore_patterns(".git", "bazel-*", "Cargo.Bazel.lock", "MODULE.bazel.lock"))
    # Repository caches can be read-only. This private copy is the only writable module.
    for path in [destination, *destination.rglob("*")]:
        path.chmod(path.stat().st_mode | (0o700 if path.is_dir() else 0o600))
    origin_lock = workspace / "MODULE.bazel.lock"
    write_json(destination / "source-resolution.json", {
        "module": module,
        "apparent_repository": apparent,
        "canonical_repository": canonical,
        "origin_module_sha256": sha256((workspace / "MODULE.bazel").read_bytes()),
        "origin_resolution_sha256": sha256(origin_lock.read_bytes()) if origin_lock.is_file() else None,
        "source_module_sha256": sha256((destination / "MODULE.bazel").read_bytes()),
        "source_cargo_lock_sha256": sha256((destination / "Cargo.lock").read_bytes()),
    })
    return destination


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, default=Path.cwd())
    parser.add_argument("--repository", default="crates", help="Apparent use_repo alias, without @")
    parser.add_argument("--cargo-lock", default="Cargo.lock")
    parser.add_argument("--bazel-lock", default="Cargo.Bazel.lock")
    parser.add_argument("--receipt", type=Path, required=True)
    parser.add_argument("--bazel", default="bazel")
    parser.add_argument("--bazel-startup-arg", action="append", default=[])
    parser.add_argument("--bazel-arg", action="append", default=[])
    parser.add_argument("--dependency", action="append", default=[], metavar="MODULE=APPARENT_REPO",
                        help="Stage and prepare a direct dependency first (root Cargo locks, @crates alias)")
    parser.add_argument("--staging-dir", type=Path)
    parser.add_argument("--overrides-rc", type=Path, help="Write required downstream module overrides here")
    args = parser.parse_args()
    args.workspace = args.workspace.resolve()
    args.receipt = args.receipt.resolve()
    if args.dependency and (not args.staging_dir or not args.overrides_rc):
        parser.error("--dependency requires --staging-dir and --overrides-rc")
    if args.overrides_rc:
        if args.overrides_rc.is_symlink():
            parser.error("The generated overrides file must not be a symlink")
        if args.overrides_rc.exists():
            if not args.overrides_rc.read_text().startswith(RC_MARKER):
                parser.error("Refusing to replace a non-generated overrides file")
            # Never let an old override affect resolution of an updated module pin.
            args.overrides_rc.unlink()
    cargo = local_path(args.workspace, args.cargo_lock)
    generated = local_path(args.workspace, args.bazel_lock)
    if (args.workspace / args.bazel_lock).is_symlink():
        parser.error("Generated metadata must not be a symlink")
    if generated == cargo or args.receipt in (cargo, generated):
        parser.error("Cargo.lock, generated metadata and receipt must be different files")
    # Invalidate the root too before staging. A failed dependency preparation must
    # not leave old root metadata usable by an accidental later build command.
    generated.unlink(missing_ok=True)
    args.receipt.unlink(missing_ok=True)
    dependencies = []
    overrides = []
    for item in args.dependency:
        module, apparent = item.split("=", 1)
        path = stage_dependency(args, args.workspace, module, apparent, args.staging_dir.resolve())
        evidence = prepare_one(args, path, "crates", "Cargo.lock", "Cargo.Bazel.lock", path / "preparation.json")
        evidence["source_resolution"] = json.loads((path / "source-resolution.json").read_text())
        write_json(path / "preparation.json", evidence)
        override = f"--override_module={module}={path}"
        args.bazel_arg.append(override)
        overrides.append(override)
        dependencies.append(evidence)
    result = prepare_one(args, args.workspace, args.repository, args.cargo_lock, args.bazel_lock, args.receipt)
    if args.overrides_rc:
        args.overrides_rc.parent.mkdir(parents=True, exist_ok=True)
        args.overrides_rc.write_text(RC_MARKER + "".join("common " + flag + "\n" for flag in overrides))
    result["dependencies"] = dependencies
    result["dependency_overrides"] = overrides
    write_json(args.receipt, result)


if __name__ == "__main__":
    main()
