#!/usr/bin/env python3
"""Generate crate_universe metadata before a SONiC Bazel build (Python 3.11+)."""

import argparse
import copy
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import tomllib
from urllib.parse import urlsplit, urlunsplit


RC_MARKER = "# Generated by sonic-build-infra tools/rust/prepare.py; do not edit.\n"


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def local_path(workspace, value):
    path = (workspace / value).resolve()
    if not path.is_relative_to(workspace):
        raise ValueError(f"Path must stay inside the workspace: {value}")
    return path


def verify_graph(cargo_bytes, generated):
    """Reject any selected package whose version or source differs from Cargo.lock."""
    packages = tomllib.loads(cargo_bytes.decode())["package"]
    by_id = {}
    for package in packages:
        key = (package["name"], package["version"])
        by_id.setdefault(key, []).append(package)
    crates = generated.get("crates")
    if not isinstance(crates, dict) or not crates:
        raise ValueError("Generated metadata has no crates")
    selected = []
    for identifier, crate in sorted(crates.items()):
        key = (crate["name"], crate["version"])
        matches = by_id.get(key, [])
        repository = crate.get("repository")
        matching = []
        for package in matches:
            source = package.get("source", "")
            if not repository:
                valid = not source
            elif "Http" in repository:
                checksum = repository["Http"].get("sha256")
                valid = (source.startswith("registry+") and bool(checksum)
                         and checksum == package.get("checksum"))
            elif "Git" in repository:
                git = repository["Git"]
                parsed = urlsplit(source.removeprefix("git+"))
                remote = urlunsplit((parsed.scheme, parsed.netloc, parsed.path, "", ""))
                valid = (source.startswith("git+") and bool(parsed.fragment)
                         and git.get("remote") == remote
                         and git.get("commitish") == {"Rev": parsed.fragment})
            else:
                valid = False
            if valid:
                matching.append(package)
        if len(matching) != 1:
            raise ValueError(f"Generated crate does not match one Cargo.lock pin: {identifier}")
        pin = matching[0]
        selected.append({field: pin[field] for field in ("name", "version", "source", "checksum") if field in pin})
    return selected


def run_bazel(args, workspace, command, arguments=(), *, env=None, capture=False):
    startup = list(args.bazel_startup_arg)
    if workspace != getattr(args, "workspace", workspace):
        # setup-bazel can set a shared output_base in an ambient bazelrc. A
        # different workspace must never reuse or kill the consumer's server.
        output_base = workspace.parent / (".bazel-output-" + workspace.name)
        startup = [flag for flag in startup if not flag.startswith("--output_base=")]
        startup.append("--output_base=" + str(output_base))
        if "--batch" not in startup:
            startup.append("--batch")
    invocation = [args.bazel, *startup, command,
                  *args.bazel_arg, "--lockfile_mode=update", *arguments]
    completed = subprocess.run(invocation, cwd=workspace, env=env, check=True,
                               text=True, stdout=subprocess.PIPE if capture else None)
    return completed.stdout if capture else invocation


def prepare_one(args, workspace, repository, cargo_name, generated_name, receipt):
    cargo = local_path(workspace, cargo_name)
    if (workspace / generated_name).is_symlink():
        raise ValueError("Generated metadata must not be a symlink")
    output = local_path(workspace, generated_name)
    if output == cargo or receipt.resolve() in (cargo, output):
        raise ValueError("Cargo.lock, generated metadata and receipt must be different files")
    before = cargo.read_bytes()
    # Resolve stale caches by regeneration, never by accepting a restored receipt.
    # The empty file lets Bazel resolve the configured source-file label first.
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(b"")
    receipt.unlink(missing_ok=True)
    env = os.environ.copy()
    env.pop("REPIN", None)
    env.pop("CARGO_BAZEL_REPIN_ONLY", None)
    env["CARGO_BAZEL_REPIN"] = "workspace"
    try:
        command = run_bazel(args, workspace, "fetch", ["--repo=@" + repository], env=env)
        if cargo.read_bytes() != before:
            raise ValueError("Preparation changed Cargo.lock; use skip_cargo_lockfile_overwrite = True")
        generated_bytes = output.read_bytes()
        graph = verify_graph(before, json.loads(generated_bytes))
        inputs = {"MODULE.bazel": sha256((workspace / "MODULE.bazel").read_bytes())}
        for name in (".bazelversion", ".bazelrc"):
            if (workspace / name).is_file():
                inputs[name] = sha256((workspace / name).read_bytes())
        # Cargo workspaces can have nested manifests; retain them as provenance.
        for manifest in workspace.rglob("Cargo.toml"):
            if not any(part.startswith((".git", "bazel-", ".cargo-bazel")) for part in manifest.relative_to(workspace).parts):
                inputs[str(manifest.relative_to(workspace))] = sha256(manifest.read_bytes())
        result = {
            "schema_version": 1,
            "workspace": str(workspace),
            "repository": repository,
            "cargo_lock": cargo_name,
            "cargo_lock_sha256": sha256(before),
            "cargo_lock_unchanged": True,
            "bazel_lock": generated_name,
            "bazel_lock_sha256": sha256(generated_bytes),
            "helper_sha256": sha256(Path(__file__).read_bytes()),
            "input_sha256": inputs,
            "selected_packages": graph,
            "command": command,
        }
        write_json(receipt, result)
        return result
    except BaseException:
        # A failed preparation must not leave a usable stale/partially written lock.
        output.unlink(missing_ok=True)
        if not cargo.is_file() or cargo.read_bytes() != before:
            cargo.write_bytes(before)
        raise


def stage_dependency(args, workspace, module, apparent, staging):
    """Fetch the already declared module; do not evaluate its crate extension yet."""
    raw_mapping = run_bazel(args, workspace, "mod", ["dump_repo_mapping", ""], capture=True)
    # Some JDKs write startup diagnostics to stdout before the NDJSON payload.
    mapping_lines = [line for line in raw_mapping.splitlines() if line.startswith("{")]
    if len(mapping_lines) != 1:
        raise ValueError("Expected one root repository mapping from Bazel")
    mapping = json.loads(mapping_lines[0])
    canonical = mapping[apparent]
    run_bazel(args, workspace, "fetch", ["--repo=@@" + canonical])
    raw_info = run_bazel(args, workspace, "info", ["output_base"], capture=True)
    paths = [Path(line) for line in raw_info.splitlines() if Path(line).is_absolute()]
    if len(paths) != 1:
        raise ValueError("Expected one absolute output_base from Bazel")
    output_base = paths[0]
    source = output_base / "external" / canonical
    if not (source / "MODULE.bazel").is_file():
        raise ValueError(f"Resolved module has no source directory: {source}")
    staging.mkdir(parents=True, exist_ok=True)
    destination = Path(tempfile.mkdtemp(prefix=module + "-", dir=staging))
    shutil.copytree(source, destination, dirs_exist_ok=True, symlinks=False,
                    ignore=shutil.ignore_patterns(".git", "bazel-*", "Cargo.Bazel.lock", "MODULE.bazel.lock"))
    # Repository caches can be read-only. This private copy is the only writable module.
    for path in [destination, *destination.rglob("*")]:
        path.chmod(path.stat().st_mode | (0o700 if path.is_dir() else 0o600))
    origin_lock = workspace / "MODULE.bazel.lock"
    write_json(destination / "source-resolution.json", {
        "module": module,
        "apparent_repository": apparent,
        "canonical_repository": canonical,
        "origin_module_sha256": sha256((workspace / "MODULE.bazel").read_bytes()),
        "origin_resolution_sha256": sha256(origin_lock.read_bytes()) if origin_lock.is_file() else None,
        "source_module_sha256": sha256((destination / "MODULE.bazel").read_bytes()),
        "source_cargo_lock_sha256": sha256((destination / "Cargo.lock").read_bytes()),
    })
    return destination


def version_matches(version, requirement):
    """Check stable Cargo version requirements; reject unsupported syntax explicitly."""
    selected = tuple(int(part) for part in version.split("+", 1)[0].split("."))
    if len(selected) != 3:
        raise ValueError(f"Expected a stable three-part Cargo version: {version}")
    for term in requirement.split(","):
        match = re.fullmatch(r"\s*(\^|~|>=|<=|>|<|=)?\s*(\d+|\*)(?:\.(\d+|\*))?(?:\.(\d+|\*))?\s*", term)
        if not match:
            raise ValueError(f"Unsupported Cargo version requirement: {requirement}")
        operator = match[1] or "^"
        parts = [part for part in match.groups()[1:] if part is not None]
        numbers = [int(part) for part in parts if part != "*"]
        if "*" in parts and parts[len(numbers):] != ["*"]:
            raise ValueError(f"Unsupported Cargo wildcard requirement: {requirement}")
        lower = tuple(numbers + [0] * (3 - len(numbers)))
        partial_upper = list(lower)
        if numbers:
            partial_upper[len(numbers) - 1] += 1
        if "*" in parts or operator == "~":
            boundary = max(0, len(numbers) - 1) if "*" in parts else (0 if len(numbers) == 1 else 1)
        else:
            boundary = next((index for index, part in enumerate(numbers) if part), max(0, len(numbers) - 1))
        upper = list(lower)
        upper[boundary] += 1
        upper[boundary + 1:] = [0] * (2 - boundary)
        if not numbers:
            valid = True
        elif operator == ">=":
            valid = selected >= lower
        elif operator == "<=":
            valid = selected <= lower if len(numbers) == 3 else selected < tuple(partial_upper)
        elif operator == ">":
            valid = selected > lower if len(numbers) == 3 else selected >= tuple(partial_upper)
        elif operator == "<":
            valid = selected < lower
        elif operator == "=":
            valid = selected[:len(numbers)] == tuple(numbers)
        else:
            valid = lower <= selected < tuple(upper)
        if not valid:
            return False
    return True


def consumer_manifests(workspace):
    root = tomllib.loads((workspace / "Cargo.toml").read_text())
    paths = [workspace / "Cargo.toml"] if "package" in root else []
    for pattern in root.get("workspace", {}).get("members", []):
        paths.extend(path / "Cargo.toml" for path in workspace.glob(pattern))
    return root, sorted(set(paths))


def validate_consumer(workspace, shared):
    """Verify native Cargo pins and requested features before using shared Bazel targets."""
    cargo = workspace / "Cargo.lock"
    native_lock = tomllib.loads(cargo.read_text())
    shared_lock = tomllib.loads((shared / "Cargo.lock").read_text())
    fields = ("name", "version", "source", "checksum")
    shared_pins = {tuple(package.get(field) for field in fields) for package in shared_lock["package"]}
    for package in native_lock["package"]:
        if package.get("source", "").startswith("registry+"):
            if tuple(package.get(field) for field in fields) not in shared_pins:
                raise ValueError(f"{workspace}: Cargo.lock pin is missing or different in shared dependencies: "
                                 f"{package['name']} {package['version']}")
    shared_deps = tomllib.loads((shared / "Cargo.toml").read_text())["dependencies"]
    root, manifests = consumer_manifests(workspace)
    inputs = {"Cargo.toml": sha256((workspace / "Cargo.toml").read_bytes())}
    checked = []
    for manifest in manifests:
        relative = str(manifest.relative_to(workspace))
        inputs[relative] = sha256(manifest.read_bytes())
        data = tomllib.loads(manifest.read_text())
        sections = [data, *data.get("target", {}).values()]
        for section in sections:
            for kind in ("dependencies", "build-dependencies", "dev-dependencies"):
                for alias, value in section.get(kind, {}).items():
                    dependency = {"version": value} if isinstance(value, str) else dict(value)
                    if dependency.get("workspace"):
                        inherited = root["workspace"]["dependencies"][alias]
                        inherited = {"version": inherited} if isinstance(inherited, str) else dict(inherited)
                        inherited["features"] = sorted(set(inherited.get("features", [])) | set(dependency.get("features", [])))
                        dependency = inherited
                    # SONiC source dependencies still compile in their owning modules.
                    if "path" in dependency or "git" in dependency:
                        continue
                    name = dependency.get("package", alias)
                    selected = shared_deps.get(name)
                    if selected is None:
                        raise ValueError(f"{relative}: shared manifest has no dependency {name}")
                    if isinstance(selected, str):
                        selected = {"version": selected}
                    candidates = [package for package in shared_lock["package"]
                                  if package["name"] == name and package.get("source", "").startswith("registry+")
                                  and version_matches(package["version"], selected["version"])]
                    if len(candidates) != 1 or not version_matches(candidates[0]["version"], dependency["version"]):
                        raise ValueError(f"{relative}: shared {name} version does not satisfy {dependency['version']}")
                    missing = set(dependency.get("features", [])) - set(selected.get("features", []))
                    if missing or (dependency.get("default-features", True) and not selected.get("default-features", True)):
                        raise ValueError(f"{relative}: shared {name} does not enable requested features: {sorted(missing)}")
                    checked.append({"manifest": relative, "kind": kind, "name": name,
                                    "version": candidates[0]["version"], "features": dependency.get("features", [])})
    return {"workspace": str(workspace), "cargo_lock_sha256": sha256(cargo.read_bytes()),
            "cargo_lock_unchanged": True, "input_sha256": inputs, "checked_dependencies": checked}


def prepare_shared(args):
    module, apparent = args.shared_dependency.split("=", 1)
    shared = stage_dependency(args, args.workspace, module, apparent, args.staging_dir.resolve())
    # Overrides for source owners belong to the consumer graph. The third-party
    # graph has no dependency on those owners and Bazel rejects unknown modules.
    generator_args = copy.copy(args)
    direct_modules = set(re.findall(r'name\s*=\s*"([^"]+)"', (shared / "MODULE.bazel").read_text()))
    direct_modules.discard(module)
    generator_args.bazel_arg = [flag for flag in args.bazel_arg
                               if not flag.startswith(("--platforms=", "--@", "--//"))
                               and (not flag.startswith("--override_module=")
                                    or flag.split("=", 2)[1] in direct_modules)]
    evidence = prepare_one(generator_args, shared, "crates", "Cargo.lock", "Cargo.Bazel.lock", shared / "preparation.json")
    evidence["source_resolution"] = json.loads((shared / "source-resolution.json").read_text())
    write_json(shared / "preparation.json", evidence)
    overrides = [f"--override_module={module}={shared}"]
    args.bazel_arg.extend(overrides)
    dependencies = []
    for item in args.dependency:
        dependency_module, dependency_apparent = item.split("=", 1)
        path = stage_dependency(args, args.workspace, dependency_module, dependency_apparent, args.staging_dir.resolve())
        dependency_evidence = validate_consumer(path, shared)
        dependency_evidence["source_resolution"] = json.loads((path / "source-resolution.json").read_text())
        dependencies.append(dependency_evidence)
        override = f"--override_module={dependency_module}={path}"
        args.bazel_arg.append(override)
        overrides.append(override)
    dependencies.extend(validate_consumer(path.resolve(), shared) for path in args.consumer_workspace)
    result = {} if args.shared_only else validate_consumer(args.workspace, shared)
    result.update({"schema_version": 2, "shared_dependency": evidence, "dependencies": dependencies,
                   "dependency_overrides": overrides, "helper_sha256": sha256(Path(__file__).read_bytes())})
    # Publish overrides only after all checks succeeded. Failed preparation cannot
    # accidentally reuse an older graph or a partially checked consumer.
    args.overrides_rc.parent.mkdir(parents=True, exist_ok=True)
    args.overrides_rc.write_text(RC_MARKER + "".join("common " + flag + "\n" for flag in overrides))
    write_json(args.receipt, result)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, default=Path.cwd())
    parser.add_argument("--repository", default="crates", help="Apparent use_repo alias, without @")
    parser.add_argument("--cargo-lock", default="Cargo.lock")
    parser.add_argument("--bazel-lock", default="Cargo.Bazel.lock")
    parser.add_argument("--receipt", type=Path, required=True)
    parser.add_argument("--bazel", default="bazel")
    parser.add_argument("--bazel-startup-arg", action="append", default=[])
    parser.add_argument("--bazel-arg", action="append", default=[])
    parser.add_argument("--dependency", action="append", default=[], metavar="MODULE=APPARENT_REPO",
                        help="Stage and prepare a direct dependency first (root Cargo locks, @crates alias)")
    parser.add_argument("--shared-dependency", metavar="MODULE=APPARENT_REPO",
                        help="Prepare one shared third-party graph instead of a graph in every consumer")
    parser.add_argument("--shared-only", action="store_true",
                        help="Prepare a shared module for registry CI; the test root has no Cargo workspace")
    parser.add_argument("--consumer-workspace", type=Path, action="append", default=[],
                        help="Also validate a local owning source checkout against the shared graph")
    parser.add_argument("--staging-dir", type=Path)
    parser.add_argument("--overrides-rc", type=Path, help="Write required downstream module overrides here")
    args = parser.parse_args()
    args.workspace = args.workspace.resolve()
    args.receipt = args.receipt.resolve()
    if (args.dependency or args.shared_dependency) and (not args.staging_dir or not args.overrides_rc):
        parser.error("--dependency and --shared-dependency require --staging-dir and --overrides-rc")
    if (args.shared_only or args.consumer_workspace) and not args.shared_dependency:
        parser.error("--shared-only and --consumer-workspace require --shared-dependency")
    if args.overrides_rc:
        if args.overrides_rc.is_symlink():
            parser.error("The generated overrides file must not be a symlink")
        if args.overrides_rc.exists():
            if not args.overrides_rc.read_text().startswith(RC_MARKER):
                parser.error("Refusing to replace a non-generated overrides file")
            # Never let an old override affect resolution of an updated module pin.
            args.overrides_rc.unlink()
    cargo = local_path(args.workspace, args.cargo_lock)
    generated = local_path(args.workspace, args.bazel_lock)
    if (args.workspace / args.bazel_lock).is_symlink():
        parser.error("Generated metadata must not be a symlink")
    if generated == cargo or args.receipt in (cargo, generated):
        parser.error("Cargo.lock, generated metadata and receipt must be different files")
    # Invalidate the root too before staging. A failed dependency preparation must
    # not leave old root metadata usable by an accidental later build command.
    generated.unlink(missing_ok=True)
    args.receipt.unlink(missing_ok=True)
    if args.shared_dependency:
        prepare_shared(args)
        return
    dependencies = []
    overrides = []
    for item in args.dependency:
        module, apparent = item.split("=", 1)
        path = stage_dependency(args, args.workspace, module, apparent, args.staging_dir.resolve())
        evidence = prepare_one(args, path, "crates", "Cargo.lock", "Cargo.Bazel.lock", path / "preparation.json")
        evidence["source_resolution"] = json.loads((path / "source-resolution.json").read_text())
        write_json(path / "preparation.json", evidence)
        override = f"--override_module={module}={path}"
        args.bazel_arg.append(override)
        overrides.append(override)
        dependencies.append(evidence)
    result = prepare_one(args, args.workspace, args.repository, args.cargo_lock, args.bazel_lock, args.receipt)
    if args.overrides_rc:
        args.overrides_rc.parent.mkdir(parents=True, exist_ok=True)
        args.overrides_rc.write_text(RC_MARKER + "".join("common " + flag + "\n" for flag in overrides))
    result["dependencies"] = dependencies
    result["dependency_overrides"] = overrides
    write_json(args.receipt, result)


if __name__ == "__main__":
    main()
